package it.unisa.parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/**
 * CUP generated class containing symbol constants.
 */
public class ParserSym {
    /* terminals */
    public static final int CHAR_CONST = 30;
    public static final int LGPAR = 15;
    public static final int CHAR = 9;
    public static final int GE = 40;
    public static final int UMINUS = 24;
    public static final int DOUBLE_CONST = 28;
    public static final int DOUBLE = 7;
    public static final int SEMI = 4;
    public static final int INT = 5;
    public static final int OUT = 18;
    public static final int MINUS = 23;
    public static final int WRITE = 21;
    public static final int INOUT = 19;
    public static final int AND = 45;
    public static final int NOT = 44;
    public static final int LT = 41;
    public static final int RPAR = 14;
    public static final int OR = 46;
    public static final int IN = 17;
    public static final int BOOL = 6;
    public static final int RGPAR = 16;
    public static final int COMMA = 10;
    public static final int DIV = 26;
    public static final int PLUS = 22;
    public static final int ASSIGN = 33;
    public static final int IF = 34;
    public static final int ID = 11;
    public static final int LE = 42;
    public static final int EOF = 0;
    public static final int INT_CONST = 27;
    public static final int TRUE = 31;
    public static final int error = 1;
    public static final int START = 3;
    public static final int EQ = 43;
    public static final int HEAD = 2;
    public static final int TIMES = 25;
    public static final int ELSE = 36;
    public static final int READ = 20;
    public static final int WHILE = 37;
    public static final int THEN = 35;
    public static final int LPAR = 13;
    public static final int STRING = 8;
    public static final int DEF = 12;
    public static final int FALSE = 32;
    public static final int STRING_CONST = 29;
    public static final int GT = 39;
    public static final int DO = 38;
    public static final String[] terminalNames = new String[]{
            "EOF",
            "error",
            "HEAD",
            "START",
            "SEMI",
            "INT",
            "BOOL",
            "DOUBLE",
            "STRING",
            "CHAR",
            "COMMA",
            "ID",
            "DEF",
            "LPAR",
            "RPAR",
            "LGPAR",
            "RGPAR",
            "IN",
            "OUT",
            "INOUT",
            "READ",
            "WRITE",
            "PLUS",
            "MINUS",
            "UMINUS",
            "TIMES",
            "DIV",
            "INT_CONST",
            "DOUBLE_CONST",
            "STRING_CONST",
            "CHAR_CONST",
            "TRUE",
            "FALSE",
            "ASSIGN",
            "IF",
            "THEN",
            "ELSE",
            "WHILE",
            "DO",
            "GT",
            "GE",
            "LT",
            "LE",
            "EQ",
            "NOT",
            "AND",
            "OR"
    };
}

